"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require("dotenv/config");
exports.default = {
    schema: 'prisma/schema.prisma',
};
